### ISSUE TITLE
关于GNL

### ISSUE THREAD

**Issue by KindredSpirithub** [KaiyuYue/cgnl-network.pytorch#12]
你好，请问SpatialCGNL代码中
t = t.view(b, 1, c * h * w)
p = p.view(b, 1, c * h * w)
g = g.view(b, c * h * w, 1)
att = torch.bmm(p, g)
x = torch.bmm(att, t)
x = x.view(b, c, h, w)
这里求出的att是一个单值，再与t相乘，这样的意义是什么？

**Comment by kaiyuyue** [comment]
Hi, here is the [answer](https://github.com/KaiyuYue/cgnl-network.pytorch/issues/11#issuecomment-555809373) for the previous same question.  Hope it could help.
