### ISSUE TITLE
Instantiating SpatialCGNL with the default parameters.

### ISSUE THREAD

**Issue by Ujjawal-K-Panchal** [KaiyuYue/cgnl-network.pytorch#13]
Hi! am I doing something wrong? I tried to instantiate `resnet.SpatialCGNL()` module feeding just required parameters `inplanes` and `planes` however it gives me an error.
*Working Directory*: `cgnl-network.pytorch/model` 
**Please find the minimal reproducing code:**
```python
from resnet import SpatialCGNL
SpatialCGNL(20, 10)
```  
 *Error Traceback:*
```python
 File "/cgnl-network.pytorch/model/resnet.py", line 138, in __init__
    self.z = nn.Conv2d(planes, inplanes, kernel_size=1, stride=1,
  File "python3.8/site-packages/torch/nn/modules/conv.py", line 340, in __init__
    super(Conv2d, self).__init__(
  File "python3.8/site-packages/torch/nn/modules/conv.py", line 24, in __init__
    if in_channels % groups != 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'
```

I believe this is because the parameter `groups` in `resnet.SpatialCGNL` is set to `None`.

**Comment by Ujjawal-K-Panchal** [comment]
If this is an actual issue, one solution is by setting `groups = 1` and modifying the corrsponding error to be triggered when `groups > 1`. i.e.:
```python
if self.groups > 1:
  print("=> WARN: SpatialCGNL block uses '{}' groups".format(self.groups), \
			  'yellow')
```

**Comment by kaiyuyue** [comment]
Thanks. I have fixed it. [commit](https://github.com/KaiyuYue/cgnl-network.pytorch/commit/2b76f38aa33f59f2b870bd8f03f3cad124c724af).

**Comment by Ujjawal-K-Panchal** [comment]
Thank you! :tada:
