### ISSUE TITLE
CGNL for Image Segmentation

### ISSUE THREAD

**Issue by usb1508** [KaiyuYue/cgnl-network.pytorch#14]
How do we use CGNL in image segmentation tasks?

**Comment by kaiyuyue** [comment]
Hello,

Whatever frameworks are used there, the **backbone** is the target place to add CGNL blocks. 

For example, in Detectron2, assuming the backbone is ResNet, the CGNL blocks should be added into [detectron2/modeling/backbone/resnet.py](https://github.com/facebookresearch/detectron2/blob/main/detectron2/modeling/backbone/resnet.py). The modification way is the same way for image classification. 

Then FPN for instance segmentation or Panoptic FPN for semantic segmentation can be built upon the CGNL-ResNet. Just like the typical way to build the meta arch for detection, segmentation, or other tasks you wanna do.

Here is the list you can refer to: [Detectron2 Backbones](https://github.com/facebookresearch/detectron2/blob/main/detectron2/modeling/backbone) and [MMDetection Backbones](https://github.com/open-mmlab/mmdetection/tree/master/mmdet/models/backbones). 
Hope this could be helpful.

**Comment by usb1508** [comment]
@KaiyuYue Thanks for the details.
