### ISSUE TITLE
Approximation about Eq. (10)

### ISSUE THREAD

**Issue by ggjy** [KaiyuYue/cgnl-network.pytorch#2]
Thanks for presenting a such interesting work.
I wonder if you use β = exp(−γ(∥θ∥^2 +∥φ∥^2)) to approximate β = exp(−γ(∥θi∥^2 +∥φj∥^2)) in Eq. (10)?

**Comment by Yuzz1020** [comment]
Have you solved this question? I have the same doubt as you do. 

According to the source code, it seems the author just used the normal matrix multiplication instead of the Taylor expansion mentioned in the paper.

**Comment by kaiyuyue** [comment]
> According to the source code, it seems the author just used the normal matrix multiplication instead of the Taylor expansion mentioned in the paper.

Hi @noNameForMe1994 , I didn't use the simple matrix multiplication to replace the Talyor expansion part. Please check out these [lines of code](https://github.com/KaiyuYue/cgnl-network.pytorch/blob/master/model/resnet.py#L268-L293).

**Comment by Yuzz1020** [comment]
> > According to the source code, it seems the author just used the normal matrix multiplication instead of the Taylor expansion mentioned in the paper.
> 
> Hi @noNameForMe1994 , I didn't use the simple matrix multiplication to replace the Talyor expansion part. Please check out these [lines of code](https://github.com/KaiyuYue/cgnl-network.pytorch/blob/master/model/resnet.py#L268-L293).

Thank you so much! I got it now.

**Comment by kaiyuyue** [comment]
Anyone could have time and resources to research on this topic, please let us know and open this issue again.
